USE DATABASE IOT;
USE SCHEMA SILVER;

-- 1. STREAM từ Bronze (Change Data Capture)
CREATE OR REPLACE STREAM BRONZE_IOT_STREAM
ON TABLE BRONZE.DEVICE_TELEMETRY  -- Bronze raw JSON table
APPEND_ONLY = TRUE;

-- 2. TASK tự động chạy mỗi 5 phút (Silver transformation)
create or replace task IOT.SILVER.SILVER_IOT_TASK
	warehouse=iot_xs
	schedule='5 MINUTE'
	when SYSTEM$STREAM_HAS_DATA('BRONZE_IOT_STREAM')
	as INSERT INTO SILVER.DEVICE_TELEMETRY_HOURLY (
  DEVICE_ID,
  SITE_ID,
  HOUR_BUCKET,

  AVG_TEMPERATURE,
  MIN_TEMPERATURE,
  MAX_TEMPERATURE,

  AVG_HUMIDITY,
  MIN_HUMIDITY,
  MAX_HUMIDITY,

  AVG_BATTERY_PCT,
  SIGNAL_RSSI_AVG,
  UPTIME_HOURS,
  DATA_USAGE_MB,
  RECORD_COUNT,

  HAS_TEMPERATURE_ALERT,
  HAS_HUMIDITY_ALERT,

  LOAD_TS
)

WITH parsed AS (
  SELECT 
    JSON_DATA AS data
  FROM BRONZE_IOT_STREAM
)

SELECT 
  data:device_id::VARCHAR AS DEVICE_ID,
  data:site_id::VARCHAR AS SITE_ID,

  DATE_TRUNC('HOUR', TRY_TO_TIMESTAMP_NTZ(data:timestamp::STRING)) AS HOUR_BUCKET,

  AVG(data:temperature::FLOAT) AS AVG_TEMPERATURE,
  MIN(data:temperature::FLOAT) AS MIN_TEMPERATURE,
  MAX(data:temperature::FLOAT) AS MAX_TEMPERATURE,

  AVG(data:humidity::FLOAT) AS AVG_HUMIDITY,
  MIN(data:humidity::FLOAT) AS MIN_HUMIDITY,
  MAX(data:humidity::FLOAT) AS MAX_HUMIDITY,

  AVG(data:battery_pct::FLOAT) AS AVG_BATTERY_PCT,
  AVG(data:signal_rssi::INT) AS SIGNAL_RSSI_AVG,

  MAX(data:uptime_hours::FLOAT) AS UPTIME_HOURS,
  SUM(data:data_usage_mb::FLOAT) AS DATA_USAGE_MB,

  COUNT(*) AS RECORD_COUNT,

  MAX(CASE 
        WHEN data:temperature::FLOAT < 2 OR data:temperature::FLOAT > 8 
        THEN TRUE ELSE FALSE 
      END) AS HAS_TEMPERATURE_ALERT,

  MAX(CASE 
        WHEN data:humidity::FLOAT < 30 OR data:humidity::FLOAT > 70 
        THEN TRUE ELSE FALSE 
      END) AS HAS_HUMIDITY_ALERT,

  CURRENT_TIMESTAMP() AS LOAD_TS

FROM parsed

GROUP BY 
  data:device_id::VARCHAR,
  data:site_id::VARCHAR,
  DATE_TRUNC('HOUR', TRY_TO_TIMESTAMP_NTZ(data:timestamp::STRING));

-- 3. BẮT ĐẦU TASK
ALTER TASK SILVER_IOT_TASK RESUME;
SHOW TASKS;